### ISSUE TITLE
(CaseClauseError) no case clause matching: nil

### ISSUE THREAD

**Issue by solars** [suvash/hulaaki#31]
Hi there,

I'm sometimes getting this error when doing the basic client examples:

```
17:33:31.045 [error] GenServer #PID<0.250.0> terminating
** (CaseClauseError) no case clause matching: nil
    (hulaaki) lib/hulaaki/connection.ex:168: Hulaaki.Connection.set_active_once/2
    (hulaaki) lib/hulaaki/connection.ex:164: Hulaaki.Connection.dispatch_message/3
    (hulaaki) lib/hulaaki/connection.ex:110: Hulaaki.Connection.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.249.0>): {:subscribe, %Hulaaki.Message.Subscribe{id: 1, requested_qoses: [0], topics: ["vlora-test/devices/lopy1/up"], type: :SUBSCRIBE}}
State: %{client: #PID<0.249.0>, remainder: "", socket: nil, transport: nil}
Client #PID<0.249.0> is alive
    (stdlib) gen.erl:169: :gen.do_call/4
    (elixir) lib/gen_server.ex:771: GenServer.call/3
    (processor) lib/hulaaki/client.ex:125: Processor.MqttClient.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

```

Does anyone know what causes this? Doesn't seem to be related to my code.

**Comment by suvash** [comment]
On a quick look, it seems related to the pattern match here https://github.com/suvash/hulaaki/blob/master/lib/hulaaki/connection.ex#L168-L171 , but I'm very curious how/why the code path hits `nil` in your client. (As I can see in that dump, that the transport is set to `nil`, which seems wrong/unusual to me)
Can you provide some more info ? eg. the client example that you've written ?

**Comment by suvash** [comment]
Closing this as you haven't provided any further example/sample code.
